### ISSUE TITLE
Radio source 

### ISSUE THREAD

**Issue by NICK-FURY-6023** [Dorian349/Radio-Discord-Bot#2]
Where can find radio url or source

**Comment by Dorian349** [comment]
You can find many radios on internet by searching on google. (I just typed "radio url link" and found a lot of them)

Hope it helps!

**Comment by NICK-FURY-6023** [comment]
No it's not working bot only join the vc but don't play any song

**Comment by Dorian349** [comment]
You can add me on discord: dev_apollo

Will try to help you.

**Comment by NICK-FURY-6023** [comment]
**yes bro done**
